#!/usr/bin/env python3
"""
Builds features/*.lua from TerkanUniversal.lua.

Every feature becomes a file that runs on its own: it loads features/_core.lua (the shared helpers of the hub:
config table, toggle/slider/dropdown helpers, notifications, targeting ...), opens a small menu with just that
feature and runs the same code as the hub. The code is taken straight from the hub, so the files follow every
update of it: change the hub, run this script, commit.

    python tools/build_features.py                      # hub = ./TerkanUniversal.lua, output = ./features
    python tools/build_features.py --hub ../x.lua --out ../features

The manifest at the bottom says which lines of the hub belong to which feature.
"""
import argparse
import io
import os
import re

BASE_URL = "https://raw.githubusercontent.com/tygovansteenpaalwork-gif/Roblox_lua_script/main/"


# --------------------------------------------------------------------------------------------- helpers

class Hub:
    def __init__(self, path):
        with io.open(path, encoding="utf-8") as f:
            self.lines = f.read().replace("\r\n", "\n").split("\n")

    def find(self, pattern, start=0):
        rx = re.compile(pattern)
        for i in range(start, len(self.lines)):
            if rx.search(self.lines[i]):
                return i
        raise SystemExit("marker not found: %r (searching from line %d)" % (pattern, start + 1))

    def banner(self, title):
        """index of the first line after the 3-line banner ('-----' / '-- tab: Title' / '-----')"""
        return self.find(r"^-- tab: " + re.escape(title)) + 2

    def banner_start(self, title):
        return self.find(r"^-- tab: " + re.escape(title)) - 1

    def text(self, a, b):
        return "\n".join(self.lines[a:b]).strip("\n")


# Markers for the ranges of the manifest:
#   "after:Title"   first line after the banner of the tab "Title"
#   "before:Title"  the first line of that tab's banner (exclusive end)
#   "at:regex"      the first line matching regex (at or after the start of the range)
#   "incl:regex"    the line AFTER the first line matching regex (to include that line at an end)
def resolve(hub, spec, start_from=0):
    kind, _, rest = spec.partition(":")
    if kind == "after":
        return hub.banner(rest)
    if kind == "before":
        return hub.banner_start(rest)
    if kind == "at":
        return hub.find(rest, start_from)
    if kind == "incl":
        return hub.find(rest, start_from) + 1
    raise SystemExit("bad marker " + spec)


def cut(hub, a, b):
    ia = resolve(hub, a)
    ib = resolve(hub, b, ia + 1)
    return hub.text(ia, ib)


# --------------------------------------------------------------------------------------------- core

CORE_HEADER = '''--[[
    Terkan features - shared core
    ------------------------------------------------------------------------------------------
    Every file in features/ loads this one first. It holds the helpers of the Terkan Universal hub that the
    features build on: the config table C, the toggle / slider / dropdown / keybind helpers, notifications,
    targeting (charOf, selectTarget ...), the render-step helpers and a window (TerkanUI).

    Generated by tools/build_features.py from TerkanUniversal.lua (itself bundled from src/) - do not edit by hand.
--]]

local BASE = "%(base)s"

return function(opts)
opts = opts or {}

'''

CORE_FOOTER = '''
----------------------------------------------------------------------
-- helpers the features share
----------------------------------------------------------------------

local function myHumanoid()
    local c = lp.Character
    return c and c:FindFirstChildOfClass("Humanoid"), c and c:FindFirstChild("HumanoidRootPart"), c
end

local function typing() return UserInputService:GetFocusedTextBox() ~= nil end

local function playerNames()
    local names = {}
    for _, plr in ipairs(Players:GetPlayers()) do
        if plr ~= lp then table.insert(names, plr.Name) end
    end
    table.sort(names, function(a, b) return a:lower() < b:lower() end)
    return names
end

-- a "Player" dropdown that fills C.SelectedPlayer and keeps its list up to date.
-- onRefresh runs after every refresh, onPick after every pick (both optional)
local function addPlayerPicker(sec, onRefresh, onPick)
    local dd = sec:Dropdown({ Text = "Player", Options = playerNames(), Flag = "SelectedPlayer", NoSave = true,
        Callback = function(v)
            C.SelectedPlayer = v
            if onPick then onPick(v) end
        end })
    local function refresh()
        dd:SetOptions(playerNames())
        if onRefresh then onRefresh() end
    end
    connect(Players.PlayerAdded, refresh)
    connect(Players.PlayerRemoving, function() task.defer(refresh) end)
    return dd
end

function U.Unload()
    if not U.Running then return end
    U.Running = false
    for _, name in ipairs(U.Binds) do pcall(function() RunService:UnbindFromRenderStep(name) end) end
    for _, c in ipairs(U.Conns) do pcall(function() c:Disconnect() end) end
    for _, fn in ipairs(U.Cleanups) do pcall(fn) end
    pcall(function() win:Destroy() end)
    getgenv()[slot] = nil
end

-- features call Ready() once their menu is built: from then on switching something may notify
U.LoadingConfig = true
local function Ready()
    U.LoadingConfig = false
    task.delay(0.8, function() U.Ready = true end)
end

'''


def build_core(hub):
    a = 7   # skip the file header comment of the hub
    b = hub.banner_start("Aimbot")
    src = "\n".join(hub.lines[a:b]).strip("\n") + "\n"

    # how the UI library is found
    src, n = re.subn(r"local UI\nif TERKANUI then.*?\nend\n", '''local UI = TERKANUI or getgenv().TERKANUI
if not UI then
    local ok, res = pcall(function() return loadstring(game:HttpGet(BASE .. "TerkanUI.lua"))() end)
    if ok and res then
        UI = res
    elseif readfile and isfile and isfile("TerkanUI.lua") then
        UI = loadstring(readfile("TerkanUI.lua"))()
    else
        error("TerkanUI.lua could not be loaded")
    end
end
''', src, count=1, flags=re.S)
    assert n == 1, "core: UI loader block not found"

    # one copy of each feature at a time (not one copy of the whole hub)
    src, n = re.subn(r"-- only one copy at a time\nif getgenv\(\)\.__TerkanUniversal then\n.*?\nend\n",
                     '-- only one copy of each feature at a time\nlocal slot = "__TerkanFeature_" .. tostring(opts.Name or "feature")\n'
                     'if getgenv()[slot] then\n    pcall(getgenv()[slot].Unload)\nend\n', src, count=1, flags=re.S)
    assert n == 1, "core: single-copy block not found"
    assert "getgenv().__TerkanUniversal = U" in src
    src = src.replace("getgenv().__TerkanUniversal = U", "getgenv()[slot] = U")

    # the window carries the feature's name
    assert '    Title = "TERKAN",' in src and '    Footer = "Terkan Universal",' in src
    src = src.replace('    Title = "TERKAN",', '    Title = string.upper(opts.Title or "TERKAN"),')
    src = src.replace('    Footer = "Terkan Universal",', '    Footer = "Terkan features",')

    # every top level local of the core is exported by name
    names = []
    for m in re.finditer(r"^local function (\w+)", src, re.M):
        names.append(m.group(1))
    for m in re.finditer(r"^local ([A-Za-z_][\w, ]*?)\s*(?:=|--|$)", src, re.M):
        for n_ in m.group(1).split(","):
            n_ = n_.strip()
            if n_ and n_ != "function":
                names.append(n_)
    names += ["myHumanoid", "typing", "playerNames", "addPlayerPicker", "Ready", "slot"]
    uniq, seen = [], set()
    for n_ in names:
        if n_ not in seen:
            seen.add(n_)
            uniq.append(n_)
    export = "return {\n" + "".join("    %s = %s,\n" % (n_, n_) for n_ in uniq) + "}\nend\n"
    return CORE_HEADER % {"base": BASE_URL} + src + CORE_FOOTER + export, uniq


# --------------------------------------------------------------------------------------------- manifest

FEATURES = []
ALIASES = []   # (alias file name, target feature name, about)


def feature(name, title, about, code, tab=None, tabvar="featureTab", secs=(), pre="", picker=None, keys=""):
    """code: list of hub ranges. tab: title of the tab that is created for the feature (features that live on a tab
    of their own in the hub create it themselves and leave this out). secs: sections created on that tab before the
    code runs, as (variable, title, side). picker: name of a section that gets a Player dropdown."""
    FEATURES.append(dict(name=name, title=title, about=about, code=code, tab=tab, tabvar=tabvar, secs=list(secs),
                         pre=pre, picker=picker, keys=keys))


def alias(name, target, about):
    ALIASES.append((name, target, about))


# ---- combat
feature("aimbot", "Aimbot", "Soft aim with five aim types, FOV circle, sticky target, team / dead / wall checks.",
        [("after:Aimbot", "at:^-- Silent aim only exists")])
feature("silent_aim", "Silent Aim", "Silent aim with hit chance and FOV. Needs an executor with hookmetamethod.",
        [("at:^-- Silent aim only exists", "before:Triggerbot")],
        pre="local aimTarget\nlocal aimCircle = makeCircle()")
feature("triggerbot", "Triggerbot", "Shoots what is under the cursor, with delay, max distance, team check and a status line.",
        [("after:Triggerbot", "before:Rage")])
feature("rage", "Rage", "Automatic combat: targeting, burst fire, positioning, spinbot, abilities and the RAGE status text.",
        [("at:^local rageTarget = nil", "before:Cursor")])
feature("cursor", "Cursor", "Custom crosshair with styles, rainbow, animations and an 'aiming at' label.",
        [("after:Cursor", "before:ESP")],
        pre="local rageTarget, aimTarget")
feature("esp", "ESP", "Player ESP: 3D box, skeleton, health bar, names, chams, tracers, plus fullbright, time of day and FOV.",
        [("after:ESP", "before:Visuals")])
feature("visuals_shader", "Visuals", "Shader look: vivid colours, future lighting, reflections, clear air, pretty water, lock time.",
        [("after:Visuals", "before:Movement")])

# ---- movement
feature("fly", "Fly", "Fly with the root's velocity (no body movers), vertical speed and smoothing.",
        [("at:^-- fly ---", "at:^-- noclip ---")],
        tab="Fly", tabvar="moveTab", secs=[("fly", "Flight & Collision", None)])
feature("noclip", "Noclip", "Walk through walls.",
        [("at:^-- noclip ---", "at:^-- anti stun \\+ anti ragdoll")],
        tab="Noclip", tabvar="moveTab", secs=[("fly", "Flight & Collision", None)])
feature("speed_jump", "Speed & Jump", "Speed, jump power, infinite jump and anti stun. WalkSpeed / JumpPower are not touched: the CFrame mover does the work.",
        [("at:^local orig = \\{\\}", "at:^-- fly ---"),
         ("at:^-- anti stun \\+ anti ragdoll", "before:Defense"),
         ("at:^local function keyDown", "at:^-- telekinesis ---")],
        tab="Speed & Jump", tabvar="moveTab",
        secs=[("move", "Speed & Jump", None), ("cfSec", "CFrame Speed", None), ("cfFlySec", "CFrame Fly & Dash", "right")])
feature("cframe_speed", "CFrame Movement", "CFrame Speed, CFrame Fly and Dash: move the character by changing its CFrame.",
        [("at:^local function keyDown", "at:^-- telekinesis ---")],
        tab="CFrame Movement", tabvar="moveTab", secs=[("cfSec", "CFrame Speed", None), ("cfFlySec", "CFrame Fly & Dash", "right")])
alias("cframe_fly", "cframe_speed", "CFrame Fly is part of cframe_speed.lua")
alias("dash", "cframe_speed", "Dash is part of cframe_speed.lua")

# ---- defense
feature("anti_fling", "Anti Fling", "Stops other players' bodies from flinging you and cancels sudden launches.",
        [("at:^-- anti fling ---", "at:^-- anti ragdoll ---")],
        tab="Anti Fling", tabvar="defTab", secs=[("aflSec", "Anti Fling", None)])
feature("anti_ragdoll", "Anti Ragdoll", "Refuses the ragdoll / hit-stun state (made for The Strongest Battlegrounds).",
        [("at:^-- anti ragdoll ---", "at:^-- anti void ---"),
         ("at:^-- anti stun \\+ anti ragdoll", "before:Defense")],
        tab="Anti Ragdoll", tabvar="defTab", secs=[("arSec", "Anti Ragdoll", None)])
feature("anti_void", "Anti Void", "Puts you back on the last solid ground when you fall below the map.",
        [("at:^-- anti void ---", "at:^-- anti aim \\+ desync")],
        tab="Anti Void", tabvar="defTab", secs=[("avSec", "Anti Void", None)])
feature("desync", "Desync & Anti Aim", "Other players see you elsewhere (stay, behind, left, right, above, lag, orbit); anti aim jitter/spin; a ghost copy shows where they see you.",
        [("at:^-- anti aim \\+ desync", "before:Player")],
        tab="Desync", tabvar="defTab", secs=[("aaSec", "Anti Aim", None), ("dsSec", "Desync", "right")])
alias("anti_aim", "desync", "Anti Aim is part of desync.lua")

# ---- player
feature("teleport_spectate", "Teleport & Spectate", "Teleport to a player, spectate, click teleport (hold a key and click).",
        [("at:^tp:Button\\(\\{ Text = \"Teleport To Player\"", "at:^-- follow ---")],
        tab="Teleport", tabvar="playerTab", secs=[("tp", "Teleport & Spectate", None)],
        pre="", picker="tp")
feature("follow", "Follow Player", "Follow a player at a distance, with a gliding automatic distance.",
        [("at:^-- follow ---", "at:^-- orbit ---")],
        tab="Follow", tabvar="playerTab", secs=[("tp", "Player", None)], picker="tp", pre="local orbitDD")
feature("orbit", "Orbit Player", "Circle around a player (circle, bob or figure eight) with lock-on.",
        [("at:^-- orbit ---", "at:^-- no animations ---")],
        tab="Orbit", tabvar="playerTab", secs=[("tp", "Player", None)], picker="tp")
feature("no_animations", "No Animations", "Stops the animations of your own character (stop all, attacks only, freeze pose).",
        [("at:^-- no animations ---", "at:^-- inventory inspector ---")],
        tab="No Animations", tabvar="playerTab")
feature("inventory_inspector", "Inventory Inspector", "Shows what a player holds and carries.",
        [("at:^-- inventory inspector ---", "at:^toggle\\(misc1, \"Anti AFK\"")],
        tab="Inventory", tabvar="playerTab", secs=[("tp", "Player", None)],
        pre="local renderInventory", picker="tp")
feature("anti_afk", "Utility", "Anti AFK and rejoin the current server.",
        [("at:^toggle\\(misc1, \"Anti AFK\"", "at:^-- whitelist & blacklist")],
        tab="Utility", tabvar="playerTab", secs=[("misc1", "Utility", None)])
alias("rejoin", "anti_afk", "Rejoin is part of anti_afk.lua")
feature("whitelist_blacklist", "Whitelist & Blacklist", "Friends are skipped by every targeting feature, blacklisted players are targeted first. Auto-whitelists Roblox friends.",
        [("at:^-- whitelist & blacklist", "incl:^end   -- lists")],
        tab="Lists", tabvar="playerTab")

# ---- fling
feature("fling", "Fling", "Fling one player or everyone (loop), Void Spam with targets and delays, and a LOADING status text.",
        [("after:Fling", "at:^;\\(function\\(\\)  -- own function: the fling block"),
         ("at:^-- tuning ---", "before:Avatar")],
        pre="")
alias("void_spam", "fling", "Void Spam is part of fling.lua")
alias("fling_all", "fling", "Fling All is part of fling.lua")
feature("punch_fling", "Punch Fling", "A real punch animation plus one short fling per punch (TSB's Normal Punch inside TSB).",
        [("at:^local flingToken, flingBusy", "at:^-- One attempt on one player"),
         ("at:^local RESULT_TEXT", "at:^-- fling ---"),
         ("at:^-- punch fling ---", "at:^end\\)\\(\\)  -- punch fling")],
        tab="Punch Fling", tabvar="flingTab",
        pre="")

# ---- avatar
feature("avatar_copy", "Avatar", "Become a copy of another player or of any Roblox user (by name or id). Only on your screen.",
        [("after:Avatar", "before:FE")])

# ---- FE
feature("spin", "Spin", "Spin your character around any axis at any speed (others see it).",
        [("at:^-- spin ---", "at:^-- headsit ---")],
        tab="Spin", tabvar="funTab", secs=[("spinSec", "Spin", None)])
feature("headsit", "Headsit", "Sit on somebody's head with the real sit animation (others see it).",
        [("at:^-- headsit ---", "at:^-- animations \\(FE\\)")],
        tab="Headsit", tabvar="funTab", secs=[("sitSec", "Headsit", None)], picker="sitSec")
feature("fe_animations", "FE Animations", "Emotes, your own animation ids, sit anywhere, lay down: animations others can see.",
        [("at:^-- animations \\(FE\\)", "at:^-- superman fly \\(FE\\)")],
        tab="FE Animations", tabvar="funTab", secs=[("animSec", "Animations", None), ("poseSec", "Poses", "right")])
alias("emotes", "fe_animations", "Emotes are part of fe_animations.lua")
feature("superman_fly", "Superman Fly", "Fly like Superman (R6 and R15, the arm pose is measured) with a hover pose; others see it.",
        [("at:^-- superman fly \\(FE\\)", "at:^-- custom skybox")],
        tab="Superman Fly", tabvar="funTab")
feature("custom_skybox", "Custom Skybox", "A drawn sky (sunset, neon night, aurora ...) or your own image as the sky. Only on your screen.",
        [("at:^-- custom skybox", "at:^end\\)\\(\\)$")],
        tab="Custom Skybox", tabvar="funTab", secs=[("skySec", "Custom Skybox", None), ("skyLook", "Sky Look", "right")])
alias("skybox", "custom_skybox", "The skybox is custom_skybox.lua")

# ---- misc
feature("clean_visuals", "Clean Visuals", "Removes screen effects, fog and particles; can switch off camera shake.",
        [("at:^-- clean visuals ---", "at:^-- freecam ---")],
        tab="Clean Visuals", tabvar="uniTab", secs=[("cleanSec", "Clean Visuals", None)])
feature("freecam", "Freecam", "Detach the camera from your character (WASD, E/Q up/down, Shift faster).",
        [("at:^-- freecam ---", "at:^-- unlimited zoom ---")],
        tab="Freecam", tabvar="uniTab", secs=[("camSec", "Camera", None)])
feature("unlimited_zoom", "Unlimited Zoom", "Removes the camera zoom limit.",
        [("at:^-- unlimited zoom ---", "at:^-- waypoints \\(")],
        tab="Zoom", tabvar="uniTab", secs=[("camSec", "Camera", None)])
feature("waypoints", "Waypoints", "Save positions with a name and teleport back (saved per game).",
        [("at:^-- waypoints \\(", "at:^-- stats HUD ---")],
        tab="Waypoints", tabvar="uniTab", secs=[("wpSec", "Waypoints", None)])
feature("stats_hud", "Stats HUD", "FPS, ping and player count in a corner.",
        [("at:^-- stats HUD ---", "at:^end\\)\\(\\)   -- universal")],
        tab="Stats HUD", tabvar="uniTab", secs=[("hudSec", "Stats HUD", None)])
feature("telekinesis", "Telekinesis", "Pulls loose parts to you and floats them in patterns (Infinity, Ring, Tornado, Galaxy ...). Others see the parts move.",
        [("at:^-- telekinesis ---", "at:^-- chat spy ---")],
        tab="Telekinesis", tabvar="miscTab")
feature("chat_spy", "Chat Spy", "A draggable window with every chat message your client receives.",
        [("at:^-- chat spy ---", "at:^end\\)\\(\\)   -- cframe / telekinesis / chat spy")],
        tab="Chat Spy", tabvar="miscTab")


# --------------------------------------------------------------------------------------------- output

FEATURE_HEADER = '''--[[
    %(title)s  -  %(name)s.lua
    %(about)s

    Runs on its own: opens a small menu with just this feature. It is the same code as in the Terkan Universal hub
    (%(repo)s), cut out by tools/build_features.py - do not edit by hand, change src/ and run tools/build.py.

    Run it:   loadstring(game:HttpGet("%(base)sfeatures/%(name)s.lua"))()
--]]

local BASE = "%(base)s"
local Core = getgenv().TerkanCore or loadstring(game:HttpGet(BASE .. "features/_core.lua"))()
local ctx = Core({ Name = "%(name)s", Title = "%(title)s" })
'''

ALIAS_TEMPLATE = '''--[[
    %(name)s.lua  -  %(about)s

    Just a pointer so this feature can be found by its own name: it runs %(target)s.lua.
    Run it:   loadstring(game:HttpGet("%(base)sfeatures/%(name)s.lua"))()
--]]

local BASE = "%(base)s"
return loadstring(game:HttpGet(BASE .. "features/%(target)s.lua"))()
'''


def identifiers(text):
    # strip comments and strings well enough for a name scan
    text = re.sub(r"--\[\[.*?\]\]", "", text, flags=re.S)
    text = re.sub(r"--[^\n]*", "", text)
    text = re.sub(r'"(?:\\.|[^"\\\n])*"', '""', text)
    text = re.sub(r"'(?:\\.|[^'\\\n])*'", "''", text)
    return set(re.findall(r"\b[A-Za-z_][A-Za-z0-9_]*\b", text))


def build_feature(hub, f, exported):
    prelude = []
    if f["tab"]:
        prelude.append('local %s = win:Tab("%s")' % (f["tabvar"], f["tab"]))
        for var, title, side in f["secs"]:
            if title is None:
                continue
            args = '"%s"' % title + (', "%s"' % side if side else "")
            prelude.append("local %s = %s:Section(%s)" % (var, f["tabvar"], args))
    if f["pre"]:
        prelude.append(f["pre"])
    if f["picker"]:
        prelude.append("local playerDD = addPlayerPicker(%s)" % f["picker"])
    body = "\n\n".join(cut(hub, a, b) for a, b in f["code"])
    code = "\n".join(prelude) + "\n\n" + body if prelude else body

    used = sorted({n for n in identifiers(code) if n in exported and n != "slot"} | {"Ready"})
    header = FEATURE_HEADER % dict(title=f["title"], name=f["name"], about=f["about"], base=BASE_URL,
                                   repo="https://github.com/tygovansteenpaalwork-gif/Roblox_lua_script")
    # ctx names as locals, in chunks of a readable width
    decl = []
    for i in range(0, len(used), 6):
        chunk = used[i:i + 6]
        decl.append("local %s = %s" % (", ".join(chunk), ", ".join("ctx." + n for n in chunk)))
    return header + "\n" + "\n".join(decl) + "\n\n" + code + "\n\nReady()\n"


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    ap = argparse.ArgumentParser()
    ap.add_argument("--hub", default=os.path.join(root, "TerkanUniversal.lua"))
    ap.add_argument("--out", default=os.path.join(root, "features"))
    args = ap.parse_args()

    hub = Hub(args.hub)
    os.makedirs(args.out, exist_ok=True)
    core, exported = build_core(hub)
    ex = set(exported)

    def write(name, text):
        with io.open(os.path.join(args.out, name), "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)

    write("_core.lua", core)
    for f in FEATURES:
        write(f["name"] + ".lua", build_feature(hub, f, ex))
    for name, target, about in ALIASES:
        write(name + ".lua", ALIAS_TEMPLATE % dict(name=name, target=target, about=about, base=BASE_URL))

    # index
    rows = ["# Terkan features", "",
            "Every feature of the Terkan Universal hub as a file of its own, so you can find it by name. Each file runs "
            "on its own (a small menu with just that feature) and is the same code as in the hub.", "",
            "```lua", 'loadstring(game:HttpGet("%sfeatures/desync.lua"))()' % BASE_URL, "```", "",
            "| File | What it does |", "| --- | --- |"]
    entries = [(f["name"], f["about"]) for f in FEATURES] + [(n, a + " (pointer)") for n, _, a in ALIASES]
    for name, about in sorted(entries):
        rows.append("| [`%s.lua`](%s.lua) | %s |" % (name, name, about))
    rows += ["", "`_core.lua` holds the shared helpers (config table, toggle/slider helpers, notifications, targeting ...). "
             "Everything here is generated (`python tools/build.py`); edit `src/` and rebuild, not these files. `manifest.json` is the machine readable index that `Terkan.lua` uses.", ""]
    write("README.md", "\n".join(rows))

    # files of features that no longer exist in the manifest are removed
    keep = {"_core.lua", "README.md"} | {f["name"] + ".lua" for f in FEATURES} | {n + ".lua" for n, _, _ in ALIASES}
    for stale in sorted(os.listdir(args.out)):
        if stale.endswith((".lua", ".md")) and stale not in keep:
            os.remove(os.path.join(args.out, stale))
            print("removed stale", stale)
    print("wrote %d features, %d pointers, core with %d exports" % (len(FEATURES), len(ALIASES), len(exported)))


if __name__ == "__main__":
    main()
